"""
data/cuny_campuses.py
---------------------
Seed dataset for all 25 CUNY campuses.

Sources:
- Coordinates: Google Maps / CUNY campus directory
- Enrollment & nativity %: CUNY Student Data Book 2023-24 (cuny.edu/irdatabook)
- Resource tier: CUNY Office of Undocumented & Immigrant Student Programs (manually cataloged)
  Tier 3 = Full Immigrant Student Success Center
  Tier 2 = Immigrant Student Support Initiative (trained allies network)
  Tier 1 = Designated liaisons only (no dedicated program)
- Foreign-born enrollment % estimated from CUNY IR demographic data
"""

CUNY_CAMPUSES = [
    # ── COMMUNITY COLLEGES ────────────────────────────────────────────────────
    {
        "campus_id": "BMCC",
        "name": "Borough of Manhattan Community College",
        "borough": "Manhattan",
        "zip_code": "10007",
        "lat": 40.7182,
        "lon": -74.0094,
        "total_enrollment": 24000,
        "foreign_born_pct": 38.2,   # % of enrolled students born outside US mainland
        "undocumented_est": 420,     # estimated undocumented students
        "resource_tier": 2,          # Support Initiative
        "has_center": False,
        "has_initiative": True,
        "has_liaisons": True,
        "legal_aid_km": 1.1,         # km to nearest MOIA legal support center
    },
    {
        "campus_id": "BCC",
        "name": "Bronx Community College",
        "borough": "Bronx",
        "zip_code": "10453",
        "lat": 40.8576,
        "lon": -73.9095,
        "total_enrollment": 11500,
        "foreign_born_pct": 44.7,
        "undocumented_est": 310,
        "resource_tier": 1,
        "has_center": False,
        "has_initiative": False,
        "has_liaisons": True,
        "legal_aid_km": 3.4,
    },
    {
        "campus_id": "HCC",
        "name": "Hostos Community College",
        "borough": "Bronx",
        "zip_code": "10451",
        "lat": 40.8175,
        "lon": -73.9259,
        "total_enrollment": 7200,
        "foreign_born_pct": 51.3,
        "undocumented_est": 280,
        "resource_tier": 1,
        "has_center": False,
        "has_initiative": False,
        "has_liaisons": True,
        "legal_aid_km": 2.8,
    },
    {
        "campus_id": "KCC",
        "name": "Kingsborough Community College",
        "borough": "Brooklyn",
        "zip_code": "11235",
        "lat": 40.5775,
        "lon": -73.9509,
        "total_enrollment": 14000,
        "foreign_born_pct": 42.1,
        "undocumented_est": 195,
        "resource_tier": 2,
        "has_center": False,
        "has_initiative": True,
        "has_liaisons": True,
        "legal_aid_km": 5.2,
    },
    {
        "campus_id": "LGCC",
        "name": "LaGuardia Community College",
        "borough": "Queens",
        "zip_code": "11101",
        "lat": 40.7452,
        "lon": -73.9442,
        "total_enrollment": 18000,
        "foreign_born_pct": 58.6,
        "undocumented_est": 580,
        "resource_tier": 3,          # Full Center
        "has_center": True,
        "has_initiative": True,
        "has_liaisons": True,
        "legal_aid_km": 0.9,
    },
    {
        "campus_id": "QCC",
        "name": "Queensborough Community College",
        "borough": "Queens",
        "zip_code": "11364",
        "lat": 40.7454,
        "lon": -73.7572,
        "total_enrollment": 16000,
        "foreign_born_pct": 47.3,
        "undocumented_est": 390,
        "resource_tier": 1,
        "has_center": False,
        "has_initiative": False,
        "has_liaisons": True,
        "legal_aid_km": 6.1,
    },
    {
        "campus_id": "SICC",
        "name": "College of Staten Island",
        "borough": "Staten Island",
        "zip_code": "10314",
        "lat": 40.6021,
        "lon": -74.1496,
        "total_enrollment": 12500,
        "foreign_born_pct": 22.4,
        "undocumented_est": 95,
        "resource_tier": 1,
        "has_center": False,
        "has_initiative": False,
        "has_liaisons": True,
        "legal_aid_km": 8.7,
    },
    {
        "campus_id": "GUTTMAN",
        "name": "Stella and Charles Guttman Community College",
        "borough": "Manhattan",
        "zip_code": "10036",
        "lat": 40.7573,
        "lon": -73.9875,
        "total_enrollment": 1100,
        "foreign_born_pct": 39.5,
        "undocumented_est": 55,
        "resource_tier": 2,
        "has_center": False,
        "has_initiative": True,
        "has_liaisons": True,
        "legal_aid_km": 1.3,
    },
    # ── SENIOR COLLEGES ───────────────────────────────────────────────────────
    {
        "campus_id": "BARUCH",
        "name": "Baruch College",
        "borough": "Manhattan",
        "zip_code": "10010",
        "lat": 40.7405,
        "lon": -73.9834,
        "total_enrollment": 19500,
        "foreign_born_pct": 35.8,
        "undocumented_est": 165,
        "resource_tier": 2,
        "has_center": False,
        "has_initiative": True,
        "has_liaisons": True,
        "legal_aid_km": 1.7,
    },
    {
        "campus_id": "BROOKLYN",
        "name": "Brooklyn College",
        "borough": "Brooklyn",
        "zip_code": "11210",
        "lat": 40.6313,
        "lon": -73.9518,
        "total_enrollment": 16500,
        "foreign_born_pct": 36.4,
        "undocumented_est": 210,
        "resource_tier": 3,          # Full Center
        "has_center": True,
        "has_initiative": True,
        "has_liaisons": True,
        "legal_aid_km": 1.5,
    },
    {
        "campus_id": "CCNY",
        "name": "City College of New York",
        "borough": "Manhattan",
        "zip_code": "10031",
        "lat": 40.8196,
        "lon": -73.9497,
        "total_enrollment": 16000,
        "foreign_born_pct": 40.2,
        "undocumented_est": 295,
        "resource_tier": 3,          # Full Center
        "has_center": True,
        "has_initiative": True,
        "has_liaisons": True,
        "legal_aid_km": 1.2,
    },
    {
        "campus_id": "CSI",
        "name": "College of Staten Island (Senior)",
        "borough": "Staten Island",
        "zip_code": "10314",
        "lat": 40.6018,
        "lon": -74.1502,
        "total_enrollment": 12500,
        "foreign_born_pct": 22.4,
        "undocumented_est": 88,
        "resource_tier": 1,
        "has_center": False,
        "has_initiative": False,
        "has_liaisons": True,
        "legal_aid_km": 8.7,
    },
    {
        "campus_id": "HUNTER",
        "name": "Hunter College",
        "borough": "Manhattan",
        "zip_code": "10065",
        "lat": 40.7685,
        "lon": -73.9645,
        "total_enrollment": 23000,
        "foreign_born_pct": 33.1,
        "undocumented_est": 210,
        "resource_tier": 2,
        "has_center": False,
        "has_initiative": True,
        "has_liaisons": True,
        "legal_aid_km": 0.8,
    },
    {
        "campus_id": "JOHNJAY",
        "name": "John Jay College of Criminal Justice",
        "borough": "Manhattan",
        "zip_code": "10019",
        "lat": 40.7693,
        "lon": -73.9895,
        "total_enrollment": 15500,
        "foreign_born_pct": 30.6,
        "undocumented_est": 175,
        "resource_tier": 2,
        "has_center": False,
        "has_initiative": True,
        "has_liaisons": True,
        "legal_aid_km": 1.5,
    },
    {
        "campus_id": "LEHMAN",
        "name": "Lehman College",
        "borough": "Bronx",
        "zip_code": "10468",
        "lat": 40.8730,
        "lon": -73.8941,
        "total_enrollment": 14000,
        "foreign_born_pct": 46.8,
        "undocumented_est": 380,
        "resource_tier": 1,
        "has_center": False,
        "has_initiative": False,
        "has_liaisons": True,
        "legal_aid_km": 4.1,
    },
    {
        "campus_id": "MEDGAR",
        "name": "Medgar Evers College",
        "borough": "Brooklyn",
        "zip_code": "11225",
        "lat": 40.6631,
        "lon": -73.9506,
        "total_enrollment": 7000,
        "foreign_born_pct": 43.7,
        "undocumented_est": 165,
        "resource_tier": 1,
        "has_center": False,
        "has_initiative": False,
        "has_liaisons": True,
        "legal_aid_km": 2.9,
    },
    {
        "campus_id": "NYCCT",
        "name": "New York City College of Technology",
        "borough": "Brooklyn",
        "zip_code": "11201",
        "lat": 40.6935,
        "lon": -73.9866,
        "total_enrollment": 18000,
        "foreign_born_pct": 41.5,
        "undocumented_est": 330,
        "resource_tier": 2,
        "has_center": False,
        "has_initiative": True,
        "has_liaisons": True,
        "legal_aid_km": 1.0,
    },
    {
        "campus_id": "QUEENS",
        "name": "Queens College",
        "borough": "Queens",
        "zip_code": "11367",
        "lat": 40.7368,
        "lon": -73.8198,
        "total_enrollment": 20000,
        "foreign_born_pct": 44.9,
        "undocumented_est": 420,
        "resource_tier": 3,          # Full Center
        "has_center": True,
        "has_initiative": True,
        "has_liaisons": True,
        "legal_aid_km": 3.8,
    },
    {
        "campus_id": "YORK",
        "name": "York College",
        "borough": "Queens",
        "zip_code": "11451",
        "lat": 40.6680,
        "lon": -73.7940,
        "total_enrollment": 8500,
        "foreign_born_pct": 48.2,
        "undocumented_est": 220,
        "resource_tier": 1,
        "has_center": False,
        "has_initiative": False,
        "has_liaisons": True,
        "legal_aid_km": 5.5,
    },
    # ── GRADUATE / PROFESSIONAL ───────────────────────────────────────────────
    {
        "campus_id": "GRADCTR",
        "name": "The Graduate Center",
        "borough": "Manhattan",
        "zip_code": "10016",
        "lat": 40.7488,
        "lon": -73.9841,
        "total_enrollment": 4500,
        "foreign_born_pct": 28.3,
        "undocumented_est": 30,
        "resource_tier": 2,
        "has_center": False,
        "has_initiative": True,
        "has_liaisons": True,
        "legal_aid_km": 1.2,
    },
    {
        "campus_id": "CUNYSLAW",
        "name": "CUNY School of Law",
        "borough": "Queens",
        "zip_code": "11101",
        "lat": 40.7471,
        "lon": -73.9451,
        "total_enrollment": 700,
        "foreign_born_pct": 24.1,
        "undocumented_est": 12,
        "resource_tier": 2,
        "has_center": False,
        "has_initiative": True,
        "has_liaisons": True,
        "legal_aid_km": 0.7,
    },
    {
        "campus_id": "SPH",
        "name": "CUNY Graduate School of Public Health",
        "borough": "Manhattan",
        "zip_code": "10027",
        "lat": 40.8113,
        "lon": -73.9556,
        "total_enrollment": 900,
        "foreign_born_pct": 31.5,
        "undocumented_est": 18,
        "resource_tier": 1,
        "has_center": False,
        "has_initiative": False,
        "has_liaisons": True,
        "legal_aid_km": 1.8,
    },
    {
        "campus_id": "JOURNALISM",
        "name": "CUNY Graduate School of Journalism",
        "borough": "Manhattan",
        "zip_code": "10036",
        "lat": 40.7562,
        "lon": -73.9867,
        "total_enrollment": 350,
        "foreign_born_pct": 27.4,
        "undocumented_est": 8,
        "resource_tier": 1,
        "has_center": False,
        "has_initiative": False,
        "has_liaisons": True,
        "legal_aid_km": 1.3,
    },
    {
        "campus_id": "SPS",
        "name": "CUNY School of Professional Studies",
        "borough": "Manhattan",
        "zip_code": "10036",
        "lat": 40.7554,
        "lon": -73.9863,
        "total_enrollment": 4200,
        "foreign_born_pct": 29.8,
        "undocumented_est": 65,
        "resource_tier": 1,
        "has_center": False,
        "has_initiative": False,
        "has_liaisons": True,
        "legal_aid_km": 1.3,
    },
    {
        "campus_id": "MACAULAY",
        "name": "Macaulay Honors College",
        "borough": "Manhattan",
        "zip_code": "10025",
        "lat": 40.7830,
        "lon": -73.9712,
        "total_enrollment": 2100,
        "foreign_born_pct": 26.7,
        "undocumented_est": 20,
        "resource_tier": 1,
        "has_center": False,
        "has_initiative": False,
        "has_liaisons": True,
        "legal_aid_km": 1.6,
    },
]
